### ISSUE TITLE
where can I get dvs_msgs/EventArray.h?

### ISSUE THREAD

**Issue by Thanh-Binh** [uzh-rpg/rpg_corner_events#1]
dvs_msgs/EventArray.h is missing. 
Could you please include them? Thanks

**Comment by ruoxianglee** [comment]
you can find dvs_msgs/EventArray.h in rpg_dvs_ros after you install the DVS/DAVIS ROS driver [https://github.com/uzh-rpg/rpg_dvs_ros](url)
