### ISSUE TITLE
Corner tracking algorithm

### ISSUE THREAD

**Issue by antoniopavlis** [uzh-rpg/rpg_corner_events#2]
Hi,

I am implementing the corner tracking algorithm for the purpose of the student project and I am interested how can i display object trajectories? Corner detecting algorithm just filters given events, but I need to display several past events.

Thank you!

**Comment by guillermogb** [comment]
Maybe you want to take a look at this other repository: https://github.com/uzh-rpg/rpg_feature_tracking_analysis

**Comment by antoniopavlis** [comment]
> Maybe you want to take a look at this other repository: https://github.com/uzh-rpg/rpg_feature_tracking_analysis

Thank you so much !!
